spring:
  profiles:
    active : local
  jmx:
    default-domain: api
  application:
    name: webapp.WgWebappApplication
  
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/thymeleaf/
    suffix: .html
    cache: false
    view-names:
    - thymeleafView/*
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp  
server:
  servlet:
    encoding:
      charset: UTF-8