spring:
  profiles:
    active : local
  jmx:
    default-domain: api
  application:
    name: webapp.WgWebappApplication
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/wealthguide/
    suffix: .html
    cache: false

server:
  servlet:
    encoding:
      charset: UTF-8