#DB
spring:
  profiles:
    include: console-logging
  home:
    datasource:
      platform: mariadb
      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://wg-dev-db02.mariadb.database.azure.com:3306/wg_home?useUnicode=true&characterEncoding=utf-8
#      username: wg_home@wg-dev-db02
      jdbc-url: jdbc:mariadb://192.168.56.1:3306/win?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 73031523
      type: com.zaxxer.hikari.HikariDataSource
      connection-timeout: 30000
      max-lifetime: 300000
      maximum-pool-size: 30
      health-check-properties:
        connectivity-check-timeout-ms: 1000
        validation-timeout: 2000
        leak-detection-threshold: 60000
        connection-test-query: SELECT 1
        minimum-idle: 80
        

#server
server:
  forward-headers-strategy: native
  port: 80
  servlet:
    context-path: '/'

sinfo:
  lip: "192.168.0.172"

        
mybatis:
  home:
    configuration:
      map-underscore-to-camel-case: true
      jdbc-type-for-null: 'NULL'
